node {

    withMaven(maven:'maven') {

        stage('Checkout') {
            git url: 'https://github.com/alokebd/spring2.7j8-euraka-ribbon-hystrix.git', credentialsId: 'alokebd', branch: 'main'
        }

        stage('Build') {
            sh 'mvn clean install'

            def pom = readMavenPom file:'pom.xml'
            print pom.version
            env.version = pom.version
        }

        stage('Image') {
            dir ('cb-discovery-service') {
                def app = docker.build "localhost:5000/cb-discovery-service:${env.version}"
                app.push()
            }
        }

        stage ('Run') {
            docker.image("localhost:5000/cb-discovery-service:${env.version}").run('-p 8761:8761 -h discovery --name discovery')
        }

        stage ('Final') {
            build job: 'cb-account-service-pipeline', wait: false
        }      

    }

}